2024-12-19 13:35:30,813 - INFO - Total epochs: 50
2024-12-19 13:35:30,814 - INFO - Length of dataset: 17516
2024-12-19 13:35:41,743 - INFO - epoch [1/50]	batch [0/1460]	time(sec) 10.58	loss 1.7732	acc 0.08%	fore pix 0.02%	back pix 99.98%	
2024-12-19 13:39:16,946 - INFO - epoch [1/50]	batch [100/1460]	time(sec) 225.74	loss 1.5169	acc 9.95%	fore pix 0.49%	back pix 99.51%	
2024-12-19 13:42:52,115 - INFO - epoch [1/50]	batch [200/1460]	time(sec) 440.91	loss 1.5673	acc 8.87%	fore pix 0.13%	back pix 99.87%	
Traceback (most recent call last):
  File "train_green_t.py", line 417, in <module>
    train_model(
  File "train_green_t.py", line 119, in train_model
    for ith_batch, batch in enumerate(dataset_loader):
  File "/home/wangc/anaconda3/envs/test1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/wangc/anaconda3/envs/test1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1207, in _next_data
    idx, data = self._get_data()
  File "/home/wangc/anaconda3/envs/test1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1163, in _get_data
    success, data = self._try_get_data()
  File "/home/wangc/anaconda3/envs/test1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1011, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/wangc/anaconda3/envs/test1/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/wangc/anaconda3/envs/test1/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt